### ISSUE TITLE
Add function similar to sqlight.with_connection

### ISSUE THREAD

**Issue by cheesemans** [VioletBuse/feather#1]
Heya! Really nice work with this package, I especially like the automatic application of PRAGMAs  when opening a connection (the default settings pretty much have the ones I'm interested in) :smiley: 

After playing around a little with it I really missed the ergonomics of sqlight.with_connection to open a connection and close it automatically once I'm done with it.

Would it be possible to add? I made a fork of this repo to tailor it a bit to my needs short term, this being a change I made I can contribute it if you like :+1:

**Comment by violetbuse** [comment]
yeah I definitely could add that

**Comment by violetbuse** [comment]
I made the change and pushed a new version.
