### ISSUE TITLE
Add PRAGMA foreign_keys to config?

### ISSUE THREAD

**Issue by cheesemans** [VioletBuse/feather#2]
I'm using foreign keys a lot and hence interested in running `PRAGMA foreign_keys = on` when I connect to my sqlite db. I can work around it by writing some custom function applying it but it would be neat if it was possible to set in the feather config.

Same story here as my previous issue, I'll gladly contribute :smiley:

**Comment by violetbuse** [comment]
oh wait, I just realized that sqlite has foreign key constraints disabled by default. will definitely add!

**Comment by violetbuse** [comment]
done and published.
